{
    'name': 'N11 Pazaryeri Entegrasyonu',
    'version': '19.0.1.0.0',
    'summary': 'N11 pazaryeri ile sipariş ve stok senkronizasyonu — SOAP API',
    'author': 'Iber Bilisim',
    'website': 'https://www.iberbilisim.com.tr',
    'category': 'eCommerce',
    'license': 'LGPL-3',
    'depends': ['iber_marketplace', 'product', 'sale', 'stock', 'mail'],
    'data': [
        'security/n11_security.xml',
        'security/ir.model.access.csv',
        'data/cron.xml',
        'views/config_views.xml',
        'views/order_views.xml',
        'views/product_listing_views.xml',
        'views/sync_wizard_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
}
