MARKETPLACE_CODES = [
    ('a101', 'A101'),
    ('akakce', 'Akakce'),
    ('aliexpress', 'AliExpress'),
    ('amazon', 'Amazon'),
    ('beymen', 'Beymen'),
    ('bisifirat', 'Bisıfırat'),
    ('boltkargo', 'BoltKargo'),
    ('boyner', 'Boyner'),
    ('bpazar', 'Bpazar'),
    ('ciceksepeti', 'Çiçeksepeti'),
    ('decoverse', 'Decoverse'),
    ('eptt', 'Eptt'),
    ('etsy', 'Etsy'),
    ('evidea', 'Evidea'),
    ('evideapazaryeri', 'Evidea Pazaryeri'),
    ('farmaborsa', 'Farmaborsa'),
    ('farmazon', 'Farmazon'),
    ('flo', 'Flo'),
    ('gg', 'GittiGidiyor'),
    ('gordumaldim', 'GördümAldım'),
    ('goturc', 'Gotürc'),
    ('hb', 'Hepsiburada'),
    ('idefix', 'İdefix'),
    ('iyifiyat', 'İyi Fiyat'),
    ('joom', 'Joom'),
    ('karaca', 'Karaca'),
    ('kintshop', 'Kintshop'),
    ('koctas', 'Koçtaş'),
    ('lcw', 'LCW'),
    ('lidyana', 'Lidyana'),
    ('modanisa', 'Modanisa'),
    ('morhipo', 'Morhipo'),
    ('n11', 'N11'),
    ('n11ff', 'N11 Depom'),
    ('n11pro', 'N11Pro'),
    ('narwoo', 'Narwoo'),
    ('needion', 'Needion'),
    ('nevade', 'Nevade'),
    ('novadan', 'Novadan'),
    ('omnitron', 'Omnitron'),
    ('op1001', 'Op1001'),
    ('ozon', 'Ozon'),
    ('pazarama', 'Pazarama'),
    ('radium', 'Radium'),
    ('sumka', 'Sumka'),
    ('teknosa', 'Teknosa'),
    ('toptantr', 'ToptanTR'),
    ('trendyol', 'Trendyol'),
    ('turkcellpasaj', 'Turkcell Pasaj'),
    ('vodafonemall', 'Vodafone Mall'),
    ('wish', 'Wish'),
    ('yapisepeti', 'Yapı Sepeti'),
    ('zebramo', 'Zebramo'),
    ('zergo', 'Zergo'),
    ('Manual', 'Manuel'),
]

CARGO_COMPANIES = [
    ('aras', 'Aras Kargo'),
    ('araskurye', 'Aras Kurye'),
    ('ase', 'ASE'),
    ('boltkargo', 'Bolt Kargo'),
    ('borusan', 'Borusan'),
    ('cainiao', 'Cainiao'),
    ('hepsijet', 'HepsiJet'),
    ('horoz', 'Horoz Lojistik'),
    ('kargoturk', 'Kargo Türk'),
    ('mng', 'MNG Kargo'),
    ('netkargo', 'Net Kargo'),
    ('pts', 'PTS'),
    ('ptt', 'PTT'),
    ('sendeo', 'Sendeo'),
    ('surat', 'Sürat Kargo'),
    ('ups', 'UPS'),
    ('yurtici', 'Yurtiçi Kargo'),
]

ORDER_STATUSES = [
    ('1', 'Yeni Sipariş'),
    ('2', 'Hazırlanıyor'),
    ('3', 'Kargoya Verilecek'),
    ('4', 'Kargoya Verildi'),
    ('5', 'Teslim Edildi'),
    ('6', 'İptal Edildi'),
    ('7', 'İade'),
    ('8', 'Tamamlandı'),
    ('9', 'Beklemede'),
    ('10', 'Onay Bekliyor'),
    ('11', 'Reddedildi'),
    ('12', 'Kısmi İptal'),
    ('13', 'Kısmi İade'),
    ('14', 'Faturalı'),
    ('15', 'Diğer'),
]

PAYMENT_TYPES = [
    ('nakit', 'Nakit'),
    ('kredi_karti', 'Kredi Kartı'),
    ('havale', 'Havale'),
    ('hepsiburada', 'HepsiBurada'),
    ('kapida_nakit', 'Kapıda Nakit'),
    ('kapida_kredi_karti', 'Kapıda Kredi Kartı'),
]
