{
    "name": "İberoDoo E-Dönüşüm",
    "version": "19.0.1.7.0",
    "summary": "UBL-TR 2.1 E-Fatura ve E-İrsaliye — Odoo 19 Enterprise native entegrasyon + çoklu ERP desteği",
    "category": "Accounting",
    "author": "İberoDoo",
    "license": "LGPL-3",
    "depends": [
        "account",
        "base",
        "base_setup",
        "stock",
    ],
    "external_dependencies": {
        "python": ["requests"],
    },
    "data": [
        "security/ir.model.access.csv",
        "security/multi_company_security.xml",
        "data/actions.xml",
        "data/document_types.xml",
        "data/profile_ids.xml",
        "data/party_id_types.xml",
        "data/ubl_tax_types.xml",
        "data/exemption_reasons.xml",
        "data/unit_codes.xml",
        "views/base/base_document_views.xml",
        "views/base/document_unit_views.xml",
        "views/base/branch_views.xml",
        "views/preview_wizard.xml",
        "views/ubl_invoice_views.xml",
        "views/menu.xml",
        "views/settings_views.xml",
        "views/erp_field_mapping_info.xml",
        "views/party_id_type_views.xml",
        "views/tax_type_views.xml",
        "views/profile_id_views.xml",
        "views/document_type_views.xml",
        "views/tax_exemption_reason_views.xml",
        "views/sub_invoices/iade_views.xml",
        "views/sub_invoices/istisna_views.xml",
        "views/sub_invoices/ihracat_views.xml",
        "views/sub_invoices/ihrackayitli_views.xml",
        "views/sub_invoices/sgk_views.xml",
        "views/sub_invoices/ebelge_views.xml",
        "views/sub_invoices/mustahsil_views.xml",
        "views/sub_invoices/ozelmatrah_views.xml",
        "views/delivery_note/ubl_delivery_note_views.xml",
        "views/delivery_note/delivery_note_direction_menus.xml",
        "views/invoice_direction_menus.xml",
        "views/odoo_integration/account_move_views.xml",
        "views/odoo_integration/stock_picking_views.xml",
        "data/sequence.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "iber_e_transform/static/src/css/iber_pdf_panel.css",
            "iber_e_transform/static/src/js/ubl_invoice_list_controller.js",
            "iber_e_transform/static/src/js/ubl_delivery_note_list_controller.js",
            "iber_e_transform/static/src/xml/ubl_invoice_list_view.xml",
            "iber_e_transform/static/src/xml/ubl_delivery_note_list_view.xml",
        ],
    },
    "installable": True,
}
